### ISSUE TITLE
Update/ Edit Dataset Info 400

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/cultivar#67] opened 2016-06-03 00:16 UTC
Updating Dataset Info doesn't work

![screen shot 2016-06-02 at 5 13 18 pm](https://cloud.githubusercontent.com/assets/2944777/15765103/a69254b8-28e5-11e6-911b-6d91956410fb.png)

<img width="1212" alt="screen shot 2016-06-02 at 5 15 18 pm" src="https://cloud.githubusercontent.com/assets/2944777/15765105/a825ee66-28e5-11e6-9c95-fb8cc8970dfe.png">

**Comment by rebeccabilbro** [comment] 2016-12-09 23:36
When you've uploaded a dataset and you're trying to edit the description, you get a client-side (bad request) error.

**Comment by lauralorenz** [comment] 2017-05-22 07:50
I couldn't reproduce this error. Closing this for now; @rebeccabilbro reopen if there is an environment you can provide where this is still an issue

**Closed by lauralorenz** 2017-05-22 07:50 UTC
Labels: Front-end, Intermediate, priority: high, type: bug
